# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-11 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rg_instructor_analytics', '0004_auto_20180504_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmenttabcache',
            name='enroll',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='enrollmenttabcache',
            name='total',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='enrollmenttabcache',
            name='unenroll',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
