# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-17 11:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rg_instructor_analytics', '0006_auto_20181023_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradestatistic',
            name='cohort_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='gradestatistic',
            unique_together=set([('course_id', 'student', 'cohort_id')]),
        ),
    ]
