# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-12-09 13:24
from __future__ import unicode_literals

from django.db import migrations


def delete_lastgradestatupdate_records(apps, schema_editor):
    LastGradeStatUpdate = apps.get_model('rg_instructor_analytics', 'LastGradeStatUpdate')
    LastGradeStatUpdate.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('rg_instructor_analytics', '0007_lastgradestatupdate_force_update_students'),
    ]

    operations = [
        migrations.RunPython(delete_lastgradestatupdate_records, reverse_code=migrations.RunPython.noop),
    ]
